
POST https://api.cryptomus.com/v1/test-webhook/payment
Content-Type: application/json
merchant: 3a008604-cf0d-4946-958f-da1fa1b50de1
sign: c8559fe4b6d596d37a516ddcd0f28299

{"order_id":"e66d74b9-a91e-4d01-97b2-3ad0c0ac541c","currency":"USDT","url_callback":"https:\/\/iamconst-m.com\/korbit_bot\/api\/swap-nft\/payment\/callback","network":"bsc","status":"paid"}