GET http://0.0.0.0:8000/bot/webhook
Content-Type: application/json

{
    "update_id": 947056043,
    "message": {
        "message_id": 50,
        "from": {
            "id": 1324611645,
            "is_bot": false,
            "first_name": "Emmanuel",
            "username": "ConstMK",
            "language_code": "en"
        },
        "chat": {
            "id": 1324611645,
            "first_name": "Emmanuel",
            "username": "ConstMK",
            "type": "private"
        },
        "date": 1697625804,
        "text": "10"
    }
}
