GET https://iamconst-m.com/korbit_bot/bot/webhook
Content-Type: application/json

{
    "update_id": 947056132,
    "callback_query": {
        "id": "5689163697703468680",
        "from": {
            "id": 1324611645,
            "is_bot": false,
            "first_name": "Emmanuel",
            "username": "ConstMK",
            "language_code": "en"
        },
        "message": {
            "message_id": 226,
            "from": {
                "id": 6428822176,
                "is_bot": true,
                "first_name": "Korbit bot",
                "username": "signalKorbit_bot"
            },
            "chat": {
                "id": 1324611645,
                "first_name": "Emmanuel",
                "username": "ConstMK",
                "type": "private"
            },
            "date": 1698915733,
            "text": "Please select below your swap potion",
            "reply_markup": {
                "inline_keyboard": [
                    [
                        {
                            "text": "DAI \ud83d\udd04 USDT",
                            "callback_data": "dai_usdt"
                        }
                    ],
                    [
                        {
                            "text": "DAI -> BUSD",
                            "callback_data": "dai_busd"
                        }
                    ],
                    [
                        {
                            "text": "USDT \ud83d\udd04 BUSD",
                            "callback_data": "usdt_busd"
                        }
                    ],
                    [
                        {
                            "text": "USDT \ud83d\udd04 DAI",
                            "callback_data": "usdt_dai"
                        }
                    ],
                    [
                        {
                            "text": "BUSD \ud83d\udd04 DAI",
                            "callback_data": "busd_dai"
                        }
                    ],
                    [
                        {
                            "text": "BUSD \ud83d\udd04 USDT",
                            "callback_data": "busd_usdt"
                        }
                    ]
                ]
            }
        },
        "chat_instance": "734372869112901104",
        "data": "nft_tracker"
    }
}