<?php

return  [
    'OpenSea',
    'Magic Eden',
    'Castle',
    'Floor',
    'Yawww',
    'Hyperspace',
    'NiftyGateway',
    'X2Y2',
    'Exchange Art',
    'Tensor',
    'Fractal',
    'Rarible',
    'Digital Eyes',
    'Solport',
    'CoralCube',
    'Holaplex',
    'FormFunction',
    'BlockAsset',
    'Solanart',
    'Tiexo',
    'Alpha Art',
    'Solsea',
    'Sudoswap',
    'Zora',
    'SuperRare',
    'LooksRare',
    'Element',
    'trader.xyz',
    'Mintable',
    'Genie',
    'Blur',
    'Superfarm',
    'Foundation',
    'Infinity',
    'OverHyped',
    'NFTX',
    'GME',
    'Soltype',
    'DualMint',
    'Cyberbrokers',
    'Hodl My Moon',
    'Gamma.io',
    'Educoin',
    'Wen Moon Market',
    'Hebys',
    'GhostMarket',
    'CRNFT',
    'Blockchain Cuties Universe',
    'NFTify',
    'TixHive',
    'OneMint',
];

